// Supabase 연결 전 사용할 샘플 데이터
import { Post } from '@/types';

export const MOCK_POSTS: Post[] = [
  {
    id: '1',
    title: '교원창업, 두 세계 사이에서',
    slug: 'professor-startup-conflict',
    excerpt: '대학 창업지원 현장에서 지켜본 교원창업의 현실. 연구자로서의 정체성과 사업가로서의 역할 사이에서 교수들은 무엇을 고민하는가.',
    content: `# 교원창업, 두 세계 사이에서\n\n대학 창업지원 현장에 있으면서 수많은 교수님들이 창업 과정에서 겪는 갈등을 목격해왔습니다.\n\n## 1. 정체성의 갈등\n\n교수는 기본적으로 연구자이자 교육자입니다. 그런데 창업을 하는 순간, 사업가의 역할이 추가됩니다...\n\n## 2. 시간의 갈등\n\n창업은 24시간이 부족합니다. 하지만 교수에게는 강의, 연구, 논문 지도라는 본업이 있습니다...\n\n## 결론\n\n역할갈등은 피할 수 없지만, 이를 어떻게 관리하느냐가 창업교원의 성패를 가릅니다.`,
    category: 'startup',
    tags: ['교원창업', '역할갈등', '대학창업', '창업지원'],
    cover_image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&q=80',
    published: true,
    created_at: '2026-03-28T09:00:00Z',
    updated_at: '2026-03-28T09:00:00Z',
    reading_time: 7,
  },
  {
    id: '2',
    title: 'Claude Code 업무 자동화 실전 후기',
    slug: 'claude-code-automation',
    excerpt: '비개발자가 Claude Code를 활용해 블로그 운영을 자동화한 경험. 코딩 없이도 가능한 AI 협업의 현실적인 모습.',
    content: `# Claude Code 업무 자동화 실전 후기\n\n저는 개발자가 아닙니다. 그런 제가 Claude Code를 활용해 개인 블로그를 만들고 자동화하게 된 이야기입니다.\n\n## 처음엔 막막했습니다\n\nNext.js, Supabase, Railway... 처음 들어보는 단어들의 조합이었습니다. 하지만 Claude Code와 대화를 시작하면서 하나씩 이해가 되기 시작했습니다.\n\n## 실제로 해본 것들\n\n1. 블로그 포스트 자동 작성\n2. Supabase에 자동 업로드\n3. 이미지 최적화\n4. SEO 메타태그 자동 생성`,
    category: 'ai_tech',
    tags: ['Claude Code', 'AI', '자동화', '비개발자'],
    cover_image: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&q=80',
    published: true,
    created_at: '2026-03-25T09:00:00Z',
    updated_at: '2026-03-25T09:00:00Z',
    reading_time: 5,
  },
  {
    id: '3',
    title: '감사가 습관이 되는 순간',
    slug: 'gratitude-habit',
    excerpt: '부상이 가르쳐준 감사의 의미. 고통이 감사의 뿌리가 될 수 있다는 것을 이제야 이해합니다.',
    content: `# 감사가 습관이 되는 순간\n\n큰 부상을 당한 이후 제 삶의 방향이 완전히 바뀌었습니다.\n\n## 부상 이전의 나\n\n건강하고 무적이라고 생각했습니다. 감사는 당연한 것이 아니라 취하는 것이었습니다.\n\n## 부상 이후\n\n일상의 모든 것이 새롭게 보이기 시작했습니다. 걷는 것, 밥 먹는 것, 가족과 함께하는 것...\n\n> "감사는 가진 것에서 찾는 것이 아니라, 잃었다가 다시 얻은 것에서 비로소 깊어진다"`,
    category: 'faith',
    tags: ['감사', '신앙', '회복', '묵상'],
    cover_image: 'https://images.unsplash.com/photo-1499209974431-9dddcece7f88?w=800&q=80',
    published: true,
    created_at: '2026-03-20T09:00:00Z',
    updated_at: '2026-03-20T09:00:00Z',
    reading_time: 6,
  },
  {
    id: '4',
    title: '아이들과 함께 성장하는 이야기',
    slug: 'growing-with-kids',
    excerpt: '부모로서 아이들에게서 배운 것들. 교육 현장의 경험이 가정에서 어떻게 살아나는가.',
    content: `# 아이들과 함께 성장하는 이야기\n\n부모가 된다는 것은 생각보다 훨씬 많은 것을 배우는 과정입니다.\n\n## 아이에게 배운 것들\n\n아이가 가르쳐준 가장 큰 교훈은 "비교는 성장을 막는다"는 것입니다.\n\n## 교육 현장과 가정\n\n교육 전문가라는 직함이 집에서는 아무 의미가 없습니다. 매일 새롭게 배웁니다.\n\n## 미래의 꿈\n\n아이들을 키우는 경험이 대안학교 교장의 꿈으로 이어졌습니다.`,
    category: 'family',
    tags: ['육아', '가족', '성장'],
    cover_image: 'https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800&q=80',
    published: true,
    created_at: '2026-03-15T09:00:00Z',
    updated_at: '2026-03-15T09:00:00Z',
    reading_time: 8,
  },
  {
    id: '5',
    title: '평생 배움의 여정',
    slug: 'lifelong-learning-journey',
    excerpt: '다양한 학문을 거쳐온 여정. 서로 다른 분야의 배움이 하나로 연결되는 과정.',
    content: `# 평생 배움의 여정\n\n처음부터 이 경로를 계획한 것은 아니었습니다. 삶이 나를 이 길로 이끌었습니다.\n\n## 학문과 현장\n\n이론과 현장, 두 세계를 오가며 배운 것들이 서로를 깊게 만들었습니다.\n\n## 배움의 연결\n\n전혀 다른 분야처럼 보였던 것들이 어느 순간 하나로 연결됩니다. 그 순간이 배움의 묘미입니다.\n\n## 지금도 배우는 중\n\nAI, 교육, 창업. 세상이 빠르게 변하고 있고, 배움도 계속됩니다.`,
    category: 'learning',
    tags: ['학습', '성장', '자기계발'],
    cover_image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&q=80',
    published: true,
    created_at: '2026-03-10T09:00:00Z',
    updated_at: '2026-03-10T09:00:00Z',
    reading_time: 9,
  },
  {
    id: '6',
    title: '레이커스 팬이 본 2025-26 시즌 분석',
    slug: 'lakers-2025-26-season-analysis',
    excerpt: '어릴 때부터 레이커스 팬이었습니다. 이번 시즌의 전술 변화와 젊은 선수들의 성장에 대한 분석.',
    content: `# 레이커스 2025-26 시즌 분석\n\n레이커스 팬이 된 건 오래 전이었습니다. 코비 브라이언트를 보면서 농구에 빠져들었습니다.\n\n## 이번 시즌 핵심 변화\n\n오펜시브 시스템의 전환이 눈에 띕니다. 포스트업 중심에서 스페이싱 공격으로...\n\n## 젊은 선수들\n\n리빌딩인지 콘텐딩인지 모호한 상황에서도 젊은 선수들의 성장이 희망입니다.\n\n## 플레이오프 전망\n\n서부 컨퍼런스 경쟁이 치열하지만, 레이커스의 저력을 믿습니다.`,
    category: 'sports',
    tags: ['NBA', '레이커스', '농구', '스포츠분석'],
    cover_image: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&q=80',
    published: true,
    created_at: '2026-03-05T09:00:00Z',
    updated_at: '2026-03-05T09:00:00Z',
    reading_time: 4,
  },
];
